version: "3.8"

services:
  web:
    build: .
    image: phinma
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - .env:/app/.env
    command: ["gunicorn", "-w", "2", "--threads", "2", "--bind", "0.0.0.0:80", "--access-logfile", "-", "--error-logfile", "-", "app.wsgi"]